spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinmoa_dev
    username: pinmoa
    password: pinmoa1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
